# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbOhoW2ppFJtfJS_TXptYO6dGRI-f2u9
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.

# %cd /content/drive/My Drive


!git config --global user.email "safakcandelen@gmail.com"
!git config --global user.name "safakcandelen"

username = "safakcandelen"
token = "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"
repo_name = "vidaProject"

!git clone https://{username}:{token}@github.com/{username}/{repo_name}.git

# Commented out IPython magic to ensure Python compatibility.

# %cd /content/drive/My Drive/vidaProject


!git add .


!git commit -m "70'den fazla ham görsel proje dosyası içersine eklendi"


!git push

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/vidaProject


!git add Full-Screw-Head-Detection.v1i.yolov8


!git commit -m "Etiketli veri kümesi eklendi, 488 artırılmış görüntü ve açıklama içeren işlenmiş YOLOv8 formatı"


!git push

!pip install ultralytics

from ultralytics import YOLO
import os



dataset_path = "/content/drive/My Drive/vidaProject/Full-Screw-Head-Detection.v1i.yolov8"
yaml_path = f"{dataset_path}/data.yaml"

print(f"Eğitim şu dosya üzerinden yapılacak: {yaml_path}")


model = YOLO('yolov8n.pt')



results = model.train(
    data=yaml_path,
    epochs=50,
    imgsz=640,
    plots=True,
    project='/content/drive/My Drive/vidaProject/runs',
    name='vida_modeli'
)

# Commented out IPython magic to ensure Python compatibility.
import shutil
import os

source_weights = "/content/drive/My Drive/vidaProject/runs/vida_modeli2/weights/best.pt"
source_results = "/content/drive/My Drive/vidaProject/runs/vida_modeli2/results.png"
source_matrix = "/content/drive/My Drive/vidaProject/runs/vida_modeli2/confusion_matrix.png"

dest_folder = "/content/drive/My Drive/vidaProject"


shutil.copy(source_weights, f"{dest_folder}/best.pt")
print("best.pt (Model Beyni) kopyalandı.")


if os.path.exists(source_results):
    shutil.copy(source_results, f"{dest_folder}/training_results.png")
    print("training_results.png (Başarı Grafiği) kopyalandı.")

if os.path.exists(source_matrix):
    shutil.copy(source_matrix, f"{dest_folder}/confusion_matrix.png")
    print("confusion_matrix.png (Karmaşıklık Matrisi) kopyalandı.")

# %cd /content/drive/My\ Drive/vidaProject
!git add best.pt training_results.png confusion_matrix.png
!git commit -m "Model eğitimi tamamlandı 96.3% mAP accuracy rate'e ulaşıldı! en iyi model best.pt olarak dosya dizinine eklendi ve performans metrik grafikleri eklendi."
!git push

from ultralytics import YOLO


model = YOLO("/content/drive/MyDrive/vidaProject/runs/vida_modeli2/weights/best.pt")


dataset_location = "/content/drive/My Drive/vidaProject/Full-Screw-Head-Detection.v1i.yolov8"

print("Test Seti üzerinde sınama yapılıyor")

metrics = model.val(
    data=f"{dataset_location}/data.yaml",
    split='test',
    imgsz=640
)


print(f"\n--- SONUÇLAR ---")
print(f"Test Seti mAP50: {metrics.box.map50}")
print(f"Test Seti mAP50-95: {metrics.box.map}")

import glob
import random
from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt


model_path = "/content/drive/MyDrive/vidaProject/runs/vida_modeli2/weights/best.pt"
model = YOLO(model_path)


test_images_path = "/content/drive/My Drive/vidaProject/Full-Screw-Head-Detection.v1i.yolov8/test/images/*.jpg"
test_files = glob.glob(test_images_path)


if not test_files:
    test_files = glob.glob("/content/drive/My Drive/vidaProject/Full-Screw-Head-Detection.v1i.yolov8/valid/images/*.jpg")

selected_files = random.sample(test_files, 3)


def get_advice(class_name):
    advice_dict = {
        'T':  ("TORX (YILDIZ)", "T-Serisi (T10-T30)", "Mavi"),
        'PH': ("PHILLIPS", "PH Uç (PH1-PH2)", "Mor"),
        'PZ': ("POZIDRIV", "PZ Uç (PZ1-PZ2)", "Yeşil"),
        'H':  ("HEX (ALYAN)", "Alyan Anahtar", "Kırmızı"),
        'SL': ("DUZ (SLOTTED)", "Düz Tornavida", "Turuncu"),
        'Reference': ("REFERANS", "Para (Boyut İçin)", "Gri")
    }
    return advice_dict.get(class_name, ("BILINMEYEN", "Manuel Kontrol", "Gri"))


print(f"Model Yüklendi. {len(test_files)} test resmi arasından 3 tanesi analiz ediliyor...\n")

for img_path in selected_files:
    results = model(img_path, verbose=False)


    img = cv2.imread(img_path)

    found_screw = False
    print(f"\n Dosya: {img_path.split('/')[-1]}")

    for r in results:
        boxes = r.boxes
        for box in boxes:

            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            class_name = model.names[cls_id]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            if conf > 0.50:
                found_screw = True
                vida_tipi, oneri, renk_kodu = get_advice(class_name)


                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)


                label = f"{vida_tipi} (%{conf*100:.0f})"
                cv2.putText(img, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)


                print(f"TESPİT: {vida_tipi}")
                print(f"ÖNERİ : {oneri}")
                print(f"Güven : %{conf*100:.2f}")

    if not found_screw:
        print("Vida tespit edilemedi.")


    cv2_imshow(img)
    print("-" * 60)

